version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: hrms_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hrms}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hrmspass}
      POSTGRES_DB: ${POSTGRES_DB:-hrms_db}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-hrms} -d $${POSTGRES_DB:-hrms_db}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    container_name: hrms_api
    environment:
      PORT: 8080
      PGHOST: db
      PGUSER: ${POSTGRES_USER:-hrms}
      PGPASSWORD: ${POSTGRES_PASSWORD:-hrmspass}
      PGDATABASE: ${POSTGRES_DB:-hrms_db}
      PGPORT: 5432
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    container_name: hrms_client
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    ports:
      - '5173:5173'
    command: ["npm","run","dev","--","--host","0.0.0.0","--strictPort","--port","5173"]
    depends_on:
      - api

volumes:
  db_data:
